# This workflow will install Python dependencies and run tests.

name: Avaandmed Actions

on:
  push:
    branches:
      - main
  pull_request:
     branches:
      - main

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.python-verson}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox-gh-actions
    - name: Run test with tox
      run: tox 
      env:
        PLATFORM: ${{matrix.os}}
        AVAANDMED_KEY: ${{secrets.AVAANDMED_KEY}} 
        AVAANDMED_KEY_ID: ${{secrets.AVAANDMED_KEY_ID}}
    - name: Upload coverage.xml to artifacts
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9' }}
      uses: actions/upload-artifact@v2
      with:
        name: tox report coverage
        path: tests/coverage.xml
        if-no-files-found: error
    - name: Upload coverage.xml to Codecov
      if: ${{matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'}}
      uses: codecov/codecov-action@v2
      with:
        token: ${{secrets.CODECOV_TOKEN}} # should be removed once repo is public
        files: ./tests/coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
